---
title: "Example: Catch & Biomass data"
author: "Steven Martell"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Catch and Biomass}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```{r, echo = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
```


For this example, the Namimbian Hake data set will be used, where an absolute abundance estimate in 1985 is available for providing statistical information about model parameters and the associated MSY distribution.

```{r}
library(catchMSY)
library(tidyr)
library(ggplot2)
library(GGally)
library(mvtnorm)
library(foreach)

.THEME <- theme_bw(20)

# Get rid of index data
# hake$data$index <- NA

# # Make up fake absolute biomass index of 3200 in 1985
# hake$data$biomass     <- rep(NA,length=length(hake$data$year))
# hake$data$biomass[21] <- 3200
# hake$data$biomass.lse <- 0.08

# # Change to uniform prior for msy
# hake$dfPriorInfo$dist[3]<-'unif'
# hake$dfPriorInfo$par1[3]<-100
# hake$dfPriorInfo$par2[3]<-400


# hake <- sample.sid(hake,500)
# hake <- sir.sid(hake,4)

# Sample weights based on negative loglikelihood & imp.wt
# imp.wt <- 1.0  # get from mvtnorm later.
# hake$wts  <- exp(-hake$nll + imp.wt)



# # plot depletion
# df2 <- with(hake,{
# 	df  <- ps.dt[code==0,]
# 	wt  <- wts[code==0]
# 	ns  <- length(wt)
# 	ix  <- sample(1:ns,ns,replace=TRUE,prob=wt)
# 	colnames(df) = data$year
# 	df <- cbind(id=1:dim(df[ix,])[1],df[ix,])
# 	return(gather(df,key,dt,-id))
# })

# p <- ggplot(df2,aes(x=as.double(key),y=dt)) 
# p <- p + stat_summary(geom="ribbon",fun.ymin="min",fun.ymax="max",alpha=0.1)
# p <- p + stat_summary(geom="ribbon", fun.data="median_hilow",alpha=0.2,fill="blue")
# p <- p + stat_summary(geom="ribbon", fun.data="mean_cl_boot",alpha=0.2,fill="red")
# p <- p + geom_line(aes(group=id),size=0.1,alpha=0.1)
# p <- p + labs(x="Year",y="Depletion") + ylim(0,1)
# print(p + .THEME)
```

